[[mouse.bindings]]
action = "Paste"
mouse = "Right"

[general]
live_config_reload = true
import = [
    'C:\Users\hamaco\AppData\Roaming\alacritty\alacritty.windows.toml',
    'C:\Users\hamaco\AppData\Roaming\alacritty\alacritty.themes.0x96f.toml',
]

[colors]
transparent_background_colors = true

[scrolling]
history = 50000

[selection]
save_to_clipboard = true
semantic_escape_chars = ''' \()"',:;<>~!@#$%^&*|+=[]{}~?│↲'''

[mouse]
