snippets:
  # Git
  - name: git status
    keyword: s
    snippet: g status -sb

  - name: git add(short)
    keyword: ga
    snippet: g add {{file}}

  - name: git add
    keyword: gAdd
    snippet: g add

  - name: git dc
    keyword: gDc
    snippet: g dc

  - name: git di
    keyword: gDi
    snippet: g di

  - name: git fo
    keyword: gFo
    snippet: g fo

  - name: git swo
    keyword: gSwo
    snippet: g swo

  - name: git commit -m
    keyword: cm
    snippet: ci -m '{{}}'
    context:
      lbuffer: ^g(it)?\s

  - name: git rebase
    keyword: gr
    snippet: g rebase {{}}

  - name: git interactive-rebase
    keyword: ir
    snippet: interactive-rebase {{master}}
    context:
      lbuffer: ^g(it)?\s

  - name: git B
    keyword: B
    snippet: git symbolic-ref --short HEAD
    evaluate: true
    context:
      lbuffer: ^g(it)?\s

  # GitHub CLI
  - name: gh pr merge -md
    keyword: pm
    snippet: pr merge -md
    context:
      lbuffer: ^gh\s

  # Docker
  - name: docker run
    keyword: d-run
    snippet: docker run --rm -it -v $(pwd):/app -w /app

  # npm
  - name: npm
    keyword: npm
    snippet: zsh -c "$XDG_CONFIG_HOME/zeno/scripts/node-package-manager.ts"
    evaluate: true
  - name: npm i
    keyword: i
    snippet: install
    context: { lbuffer: '^(npm|pnpm)\s' }
  - name: yarn add
    keyword: i
    snippet: add
    context: { lbuffer: '^yarn\s' }

  # Terraform
  - name: terraform
    keyword: tf
    snippet: terraform

  - name: terraform plan
    keyword: p
    snippet: plan
    context:
      lbuffer: ^terraform\s

  - name: terraform apply
    keyword: ap
    snippet: apply
    context:
      lbuffer: ^terraform\s

  # tmux
  - name: tmux a
    keyword: tm
    snippet: tmux a || tmux

  # cd
  - name: cd -
    keyword: "-"
    snippet: cd -

  # ls
  - name: sl
    keyword: sl
    snippet: ls

  - name: ls -a
    keyword: la
    snippet: ls -a

  - name: ls -l
    keyword: ll
    snippet: ls -l

  # Others
  - name: ncu
    keyword: ncu
    snippet: npx npm-check-updates

  - name: My IP
    keyword: myip
    snippet: curl ifconfig.io

  - name: ymd
    keyword: ymd
    snippet: date "+%Y%m%d"
    evaluate: true
    context:
      lbuffer: '.+\s'

.default-options: &default-options
  --exit-0: true
  --select-1: true
  --tiebreak: begin,index
  --height: 60%
  --cycle: true
  --preview-window: right:50%

.multi-options: &multi-options
  <<: *default-options
  --multi: true

.format-options: &format-options
  <<: *default-options
  --nth: "3"

completions:
  - name: file
    patterns:
      - ^\s*(bat|cat|delta|diff|e|grep|head|hexdump|hexyl|less|nvim|sed|tail|vim|vi)(\s+\S+)*\s+$
    sourceCommand: fd --color=always --type=f
    options:
      <<: *multi-options
      --preview: fzf-preview-file {}
    callback: sed 's/ /\\ /g' | paste -s -d ' ' -

  - name: kill
    patterns:
      - "^kill( -9)? $"
    sourceCommand: "procs --color=always"
    options:
      --multi: true
      --prompt: "'Kill Process> '"
    callback: "awk '{print $1}'"
