if exists ruby && exists hub; then
	#fpath=($(dirname $0)/completions $fpath)
	eval "$(hub alias -s)"
fi

alias g="git"
alias gist="gist -cop"

alias gst="git status -sb"

alias gs="git svn"
alias gsr="git svn rebase"
alias gsd="git svn dcommit"
