if exists ruby && exists hub; then
  fpath=($(dirname $0)/completions $fpath)
  function git() { hub "$@" }
fi

alias g="git"
alias gist="gist -cop"

alias s="git status -sb"
alias gst="echo バーカ"

alias gs="git svn"
alias gsr="git svn rebase"
alias gsd="git svn dcommit"
alias gsf="git svn fetch"

alias ggpush="git push origin \$(git current-branch)"
