" === My functions ===
function! s:set_font(fontname, fontsize)
  let fontname = join(split(a:fontname, '\s'), '\ ')
  if has("gui_gtk2")
    let font = fontname . '\ ' . a:fontsize
  else
    let font = fontname . ":h" . a:fontsize
  endif
  execute "set guifont=" . font
endfunction

colorscheme spacegray

set guioptions-=e

if has("mac")
  " call s:set_font("NFモトヤバーチ1等幅", 18)
  " call s:set_font("Osaka-Mono", 16)
  " call s:set_font("Menlo Regular", 15)
  " call s:set_font("nukamiso", 15)
  " call s:set_font("Gen Jyuu Gothic Monospace Medium", 15)
  call s:set_font("SourceCodePro-Light", 14)
  set guifontwide=Capanito-L-Mono

  if has('vim_starting')
    set columns=177
    set lines=43
    set cmdheight=1
    set linespace=1
  endif

  set transparency=10
  let g:transparency = &transparency
  function! s:relative_transparency(diff)
    let &transparency = a:diff + &transparency
    let g:transparency = &transparency
  endfunction

  nnoremap <up>   :<C-u>call <SID>relative_transparency(5)<CR>
  inoremap <up>   <C-o>:call <SID>relative_transparency(5)<CR>
  nnoremap <down> :<C-u>call <SID>relative_transparency(-5)<CR>
  inoremap <down> <C-o>:call <SID>relative_transparency(-5)<CR>
elseif has("unix")
  call s:set_font("RuikaMono-03 Thin", 12)
  call s:set_font("nukamiso", 12)

  if has('vim_starting')
    set columns=140
    set lines=55
    set linespace=1
  endif
else
  call s:set_font("Ricty_Discord", 12)
  if has('vim_starting')
    set columns=125
    set lines=50
    set cmdheight=1
    set linespace=1
  endif
endif
