" === My functions ===
function! s:set_font(fontname, fontsize)
  let fontname = join(split(a:fontname, '\s'), '\ ')
  if has("gui_gtk2")
    let font = fontname . '\ ' . a:fontsize
  else
    let font = fontname . ":h" . a:fontsize
  endif
  execute "set guifont=" . font
endfunction



colorscheme vydark

if has("mac")
  " call s:set_font("Source Code Pro", 14)
  " call s:set_font("セプテンバーＭ-等幅教漢", 16)
  call s:set_font("ルイカ等幅-０３", 16)

  if has('vim_starting')
    " set columns=140
    " set lines=55
  endif

  set transparency=20
  let g:transparency = &transparency
  function! s:relative_transparency(diff)
    let &transparency = a:diff + &transparency
    let g:transparency = &transparency
  endfunction

  nnoremap <up>   :<C-u>call <SID>relative_transparency(5)<CR>
  inoremap <up>   <C-o>:call <SID>relative_transparency(5)<CR>
  nnoremap <down> :<C-u>call <SID>relative_transparency(-5)<CR>
  inoremap <down> <C-o>:call <SID>relative_transparency(-5)<CR>
elseif has("unix")
  call s:set_font("RuikaMono-03 Thin", 12)
  call s:set_font("nukamiso", 12)

  if has('vim_starting')
    set columns=140
    set lines=55
    set linespace=1
  endif
endif
