if [ ! -d $(dirname $0)/antigen ]; then
  git clone git://github.com/zsh-users/antigen.git $(dirname $0)/antigen
fi
source $(dirname $0)/antigen/antigen.zsh


antigen bundle zsh-users/zsh-completions src

antigen bundle zsh-users/zsh-syntax-highlighting

antigen bundle rhysd/zsh-bundle-exec

antigen bundle mollifier/cd-gitroot
autoload -Uz cd-gitroot
alias u='cd-gitroot'

antigen bundle mollifier/cd-bookmark
autoload -Uz cd-bookmark
alias b='cd-bookmark'

antigen bundle supercrabtree/k

export SYS_NOTIFIER="/usr/local/bin/terminal-notifier"
export NOTIFY_COMMAND_COMPLETE_TIMEOUT=10
# antigen bundle marzocchi/zsh-notify
antigen bundle shrkw/zsh-notify --branch=tmux_support
