# if [ ! -d $(dirname $0)/antigen ]; then
#   git clone git://github.com/zsh-users/antigen.git $(dirname $0)/antigen
# fi
# source $(dirname $0)/antigen/antigen.zsh
# 
# 
# antigen bundle zsh-users/zsh-completions src
# 
# ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets root)
# antigen bundle zsh-users/zsh-syntax-highlighting
# 
# # TODO: git とか ls とかでも Enter の後に引っかかるので無効化した
# # antigen bundle rhysd/zsh-bundle-exec
# 
# antigen bundle mollifier/cd-gitroot
# autoload -Uz cd-gitroot
# alias u='cd-gitroot'
# 
# antigen bundle mollifier/cd-bookmark
# autoload -Uz cd-bookmark
# alias b='cd-bookmark'
# 
# antigen bundle mollifier/zload
# autoload -Uz zload
# 
# antigen bundle supercrabtree/k
# 
# export SYS_NOTIFIER="/usr/local/bin/terminal-notifier"
# export NOTIFY_COMMAND_COMPLETE_TIMEOUT=10
# # antigen bundle marzocchi/zsh-notify
# # antigen bundle shrkw/zsh-notify --branch=tmux_support


export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "mollifier/anyframe"

zplug "mollifier/cd-gitroot"
alias u='cd-gitroot'

zplug "kwhrtsk/docker-fzf-completion"

zplug "zsh-users/zsh-autosuggestions"
# bindkey '^' autosuggest-execute

if ! zplug check --verbose; then
    printf "Install zplug plugins? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi
zplug load
