if exists peco; then
  source_files $(dirname $0)/sources/*.zsh

  # select-history
  bindkey '^r' peco-select-history

  # git-resetn-breanches
  bindkey '^x^b' peco-git-recent-branches
  bindkey '^xb'  peco-git-recent-all-branches

  # cdr
  bindkey '^x;' peco-cdr

  # ghq-look
  bindkey '^s' peco-ghq-look

  # snippets
  bindkey '^x^x' peco-snippets

  # alias
  p() { peco | while read LINE; do $@ $LINE; done  }
  alias o='git ls-files | p open'

  function peco-git-add() {
    git add  $(git status --porcelain | peco --query "$LBUFFER" | awk -F ' ' '{print $NF}')
  }

  function agvim() {
    vim $(ag $@ | peco --query "$LBUFFER" | awk -F : '{print "-c " $2 " " $1}')
  }

  alias -g B='$(git for-each-ref --format="%(refname)" refs/heads refs/remotes | peco | perl -pne "s{^refs/(heads|remotes)/}{}")'
fi
