if exists tmux; then
  tmux() {
    if [ -n "$TMUX" ]; then
      echo "Error: tmux session has been already attached"
      return 1
    fi

    if [[ ( $OSTYPE == darwin* ) && ( -x $(which reattach-to-user-namespace 2>/dev/null) ) ]]; then
      # on OS X force tmux's default command to spawn a shell in the user's namespace
      tmux_config=$(cat $HOME/.tmux.conf <(echo 'set-option -g default-command "reattach-to-user-namespace -l $SHELL"'))
      =tmux -f <(echo "$tmux_config") new-session
      # echo "$tmux_config"
    else
      =tmux new-session
    fi
  }

  tmuxx() {
    =tmux attach -d || tmux
  }
fi

case "${TERM}" in
  screen*)
    function ssh_tmux() {
      eval server=\${$#}
      =tmux new-window -n s:$server "ssh $*"
    }
    alias ssh=ssh_tmux
    ;;
esac
